version: '3.9'

networks:
  app_subnet:
    driver: bridge
    ipam:
      config:
        - subnet: 172.20.0.0/24

services:
  chatapp:
    build:
      context: .
      dockerfile: ChatApp/Dockerfile
    ports:
      - 8080:8080
    environment:
      - Redis__ConnectionString=172.20.0.30,connectRetry=3000,connectTimeout=12000,abortConnect=false
    depends_on:
      - redis
    networks:
      app_subnet:

  redis:
    image: 'redis:7.0'
    container_name: 'redis'
    command: 'redis-server'
    networks:
      app_subnet:
        ipv4_address: 172.20.0.30